[package]
name = "bytestream-rs"
version = "0.1.0"
edition = "2021"
authors = ["amaanq"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.24"
byteorder = "1.4.3"
